# Generated by Django 3.1.1 on 2020-09-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='long',
            new_name='lon',
        ),
    ]
