# Generated by Django 3.1.1 on 2020-09-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200914_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AddField(
            model_name='address',
            name='elev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
