# Generated by Django 3.1.1 on 2020-09-27 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200914_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=1, max_length=11, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(regex='^\\d+$')]),
            preserve_default=False,
        ),
    ]
