# Generated by Django 3.1.1 on 2020-09-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200911_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(blank=True, to='orders.FeatureProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.ManyToManyField(blank=True, to='orders.PresentationProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='orders.SizeProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.subtypeproduct'),
        ),
        migrations.AlterField(
            model_name='subtypeproduct',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='orders.SubTypeProduct'),
        ),
    ]
