# Generated by Django 3.1.1 on 2020-09-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200912_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.subtypeproduct'),
        ),
    ]
