# Generated by Django 3.1.1 on 2020-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200912_1500'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('product', 'presentation', 'size'), name='unique_price'),
        ),
    ]
