# Generated by Django 3.1.1 on 2020-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200912_1522'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(presentation__isnull=True), fields=('product', 'size'), name='unique_price_without_presentation'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(size__isnull=True), fields=('product', 'presentation'), name='unique_price_without_size'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('presentation__isnull', True), ('size__isnull', True)), fields=('product',), name='unique_price_without_presentation_and_size'),
        ),
    ]
