# Generated by Django 3.1.1 on 2020-09-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('orders', '0010_auto_20200912_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='logo',
            field=models.ImageField(default=1, upload_to='place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.address'),
        ),
    ]
