# Generated by Django 3.1.1 on 2020-09-28 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200927_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('takeaway', 'takeaway'), ('delivery', 'delivery'), ('local', 'local')], default='takeaway', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipping',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
