# Generated by Django 3.1.1 on 2020-10-02 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delete',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
