# Generated by Django 3.1.1 on 2020-10-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20201002_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='shipping',
            field=models.ManyToManyField(related_name='place', to='orders.Shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.place'),
            preserve_default=False,
        ),
    ]
