# Generated by Django 3.1.1 on 2020-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20201003_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipping', 'shipping'), ('open', 'open'), ('cancel', 'cancel'), ('pending', 'pending'), ('processing', 'processing'), ('delivering', 'delivering'), ('ready', 'ready')], default='pending', max_length=10),
        ),
    ]
