# Generated by Django 3.1.1 on 2020-10-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_delivery_address'),
        ('orders', '0017_auto_20201001_2158'),
    ]

    operations = [
    ]
